// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

pub(crate) fn reflens_list_objects_v2_output_output_next_continuation_token(
    input: &crate::operation::list_objects_v2::ListObjectsV2Output,
) -> ::std::option::Option<&::std::string::String> {
    let input = match &input.next_continuation_token {
        ::std::option::Option::None => return ::std::option::Option::None,
        ::std::option::Option::Some(t) => t,
    };
    ::std::option::Option::Some(input)
}
