// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn type_erase_result<O, E>(
    result: ::std::result::Result<O, E>,
) -> ::std::result::Result<
    ::aws_smithy_runtime_api::client::interceptors::context::Output,
    ::aws_smithy_runtime_api::client::orchestrator::OrchestratorError<
        ::aws_smithy_runtime_api::client::interceptors::context::Error,
    >,
>
where
    O: ::std::fmt::Debug + ::std::marker::Send + ::std::marker::Sync + 'static,
    E: ::std::error::Error + std::fmt::Debug + ::std::marker::Send + ::std::marker::Sync + 'static,
{
    result
        .map(|output| {
            ::aws_smithy_runtime_api::client::interceptors::context::Output::erase(output)
        })
        .map_err(|error| {
            ::aws_smithy_runtime_api::client::interceptors::context::Error::erase(error)
        })
        .map_err(::std::convert::Into::into)
}

pub fn parse_http_error_metadata(
    _response_status: u16,
    response_headers: &::aws_smithy_runtime_api::http::Headers,
    response_body: &[u8],
) -> Result<
    ::aws_smithy_types::error::metadata::Builder,
    ::aws_smithy_json::deserialize::error::DeserializeError,
> {
    crate::json_errors::parse_error_metadata(response_body, response_headers)
}
pub(crate) mod shape_invoke;

pub(crate) mod shape_invoke_input;

pub(crate) fn or_empty_doc(data: &[u8]) -> &[u8] {
    if data.is_empty() {
        b"{}"
    } else {
        data
    }
}

pub(crate) mod shape_invoke_output;

pub(crate) mod shape_ec2_access_denied_exception;
pub(crate) mod shape_ec2_throttled_exception;
pub(crate) mod shape_ec2_unexpected_exception;
pub(crate) mod shape_efs_mount_connectivity_exception;
pub(crate) mod shape_efs_mount_failure_exception;
pub(crate) mod shape_efs_mount_timeout_exception;
pub(crate) mod shape_efsio_exception;
pub(crate) mod shape_eni_limit_reached_exception;
pub(crate) mod shape_invalid_parameter_value_exception;
pub(crate) mod shape_invalid_request_content_exception;
pub(crate) mod shape_invalid_runtime_exception;
pub(crate) mod shape_invalid_security_group_id_exception;
pub(crate) mod shape_invalid_subnet_id_exception;
pub(crate) mod shape_invalid_zip_file_exception;
pub(crate) mod shape_kms_access_denied_exception;
pub(crate) mod shape_kms_disabled_exception;
pub(crate) mod shape_kms_invalid_state_exception;
pub(crate) mod shape_kms_not_found_exception;
pub(crate) mod shape_recursive_invocation_exception;
pub(crate) mod shape_request_too_large_exception;
pub(crate) mod shape_resource_conflict_exception;
pub(crate) mod shape_resource_not_found_exception;
pub(crate) mod shape_resource_not_ready_exception;
pub(crate) mod shape_service_exception;
pub(crate) mod shape_snap_start_exception;
pub(crate) mod shape_snap_start_not_ready_exception;
pub(crate) mod shape_snap_start_timeout_exception;
pub(crate) mod shape_subnet_ip_address_limit_reached_exception;
pub(crate) mod shape_too_many_requests_exception;
pub(crate) mod shape_unsupported_media_type_exception;
