// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_grantee(
    input: &crate::types::Grantee,
    writer: ::aws_smithy_xml::encode::ElWriter,
) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    let mut writer = writer;
    {
        writer.write_attribute("xsi:type", input.r#type.as_str());
    }
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    if let Some(var_1) = &input.display_name {
        let mut inner_writer = scope.start_el("DisplayName").finish();
        inner_writer.data(var_1.as_str());
    }
    if let Some(var_2) = &input.email_address {
        let mut inner_writer = scope.start_el("EmailAddress").finish();
        inner_writer.data(var_2.as_str());
    }
    if let Some(var_3) = &input.id {
        let mut inner_writer = scope.start_el("ID").finish();
        inner_writer.data(var_3.as_str());
    }
    if let Some(var_4) = &input.uri {
        let mut inner_writer = scope.start_el("URI").finish();
        inner_writer.data(var_4.as_str());
    }
    scope.finish();
    Ok(())
}
